name: Run Validation Script
on:
  push:
    branches: [ main ]
    paths:
      # Automatically run the script when changes are pushed to validation dir.
      - validation/**
  pull_request:  
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:
    inputs:
      validationDir:
        description: 'The directory to be validated.'
        # By default, all the files inside the validation dir will be validated.
        default: ''

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
        - name: Fetch Sources
          uses: actions/checkout@v3

        # Validate wrapper
        - name: Gradle Wrapper Validation
          uses: gradle/wrapper-validation-action@v1.0.4

        # Setup Java 11 environment for the next steps
        - name: Setup Java
          uses: actions/setup-java@v3
          with:
            distribution: zulu
            java-version: 11
        - name: Make gradlew executable
          run: chmod +x ./build/gradlew
        - name: Build with Gradle
          env: # Or as an environment variable
           SCRIPTING_LICENSE_KEY: ${{secrets.SCRIPTING_LICENSE_KEY}}
          run: cd build; ./gradlew runValidation -PvalidationDir=${{ github.event.inputs.validationDir }} --info --stacktrace
       
        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@v4.4.1
          with:
            folder: report # The folder the action should deploy.
