name: Run Transformation Script
on:
  push:
    branches: [ main ]
    paths:
      # Automatically run the script when changes are pushed to transform dir.
      - transform/**
  pull_request:  
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:
    inputs:
      inputFile:
        description: 'File to be transformed:'
        # By default, the dita-gear-pump/gear-pump.ditamap will be transformed.
        default: 'dita-gear-pump/gear-pump.ditamap'
      scenarioName:
        description: 'Scenario name (default Oxygen scenarios, or a custom scenario from project):'
        # By default, the DITA HTML5 scenario will be used.
        default: 'DITA HTML5'

jobs:
  transform:
    runs-on: ubuntu-latest

    steps:
        - name: Fetch Sources
          uses: actions/checkout@v3
        # Setup Java 11 environment for the next steps
        - name: Setup Java
          uses: actions/setup-java@v3
          with:
            distribution: zulu
            java-version: 11
        - name: Make gradlew executable
          run: chmod +x ./build/gradlew
        - name: Transform file
          env: # Or as an environment variable
           SCRIPTING_LICENSE_KEY: ${{secrets.SCRIPTING_LICENSE_KEY}}
          run: cd build; ./gradlew runTransformation -PinputFile="${{ github.event.inputs.inputFile }}" -PscenarioName="${{ github.event.inputs.scenarioName }}"  --info --stacktrace
       
        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@v4.4.1
          with:
            folder: out # The folder the action should deploy.
